#! /bin/sh

set -e

cd "$(dirname "$0")"
SOURCE_CODE="power-led-btn.py"
EXECUTABLE="power-led-btn.sh"

echo "Installing listener..."
sudo cp $SOURCE_CODE /usr/local/bin/
sudo chmod +x /usr/local/bin/$SOURCE_CODE

sudo cp $EXECUTABLE /etc/init.d/
sudo chmod +x /etc/init.d/$EXECUTABLE

sudo update-rc.d $EXECUTABLE defaults
sudo /etc/init.d/$EXECUTABLE start
echo "Listener was installed"