#! /bin/sh

set -e

cd "$(dirname "$0")"
SOURCE_CODE="power-led-btn.py"
EXECUTABLE="power-led-btn.sh"

sudo update-rc.d $EXECUTABLE remove
sudo /etc/init.d/$EXECUTABLE stop

echo "Removing listener..."
sudo rm -rf /usr/local/bin/$SOURCE_CODE
sudo rm -rf /etc/init.d/$EXECUTABLE 

echo "Listener was uninstalled"